# Generated by Django 4.1.4 on 2022-12-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "entries"},
        ),
        migrations.AlterField(
            model_name="entry",
            name="text",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
